// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the exporter/explorviz component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("explorviz")
	ScopeName = "github.com/ExplorViz/otel-collector/exporter/explorvizexporter"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
