receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :55678

processors:
  explorviz_parsing:
    validate_tokens: false
  attributes/add_default_landscape_token:
    actions:
      - key: explorviz.token.id
        value: "mytokenvalue"
        action: insert
      - key: explorviz.token.secret
        value: "mytokensecret"
        action: insert

exporters:
  explorviz:
    broker: localhost:9091
    topic: telemetry.entities

  clickhouse:
    endpoint: tcp://localhost:19000
    create_schema: false

  debug:
    verbosity: detailed

extensions:
  explorviz_token_validator:
    broker: localhost:9091
    topic: tokens.events

service:
  extensions: [explorviz_token_validator]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [explorviz_parsing]
      exporters:
        - explorviz
        - clickhouse
        # - debug # Uncomment for direct output to stdout
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
