// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/explorviz_parsing component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("explorviz_parsing")
	ScopeName = "github.com/ExplorViz/otel-collector/processor/explorvizparsingprocessor"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
