syntax = "proto3";

option go_package = "github.com/ExplorViz/otel-collector/common/genproto/telemetrypb";

message TelemetryEntity {
  string landscape_token_id = 1;
  string landscape_token_secret = 2;

  optional string git_commit_hash = 4;

  oneof entity_descriptor {
    CodeDescriptor code_descriptor = 5;
  }
}

message CodeDescriptor {
  string application_name = 1;

  string file_id = 2; // Lookup key for retrieving telemetry for this file
  string file_path = 3; // File path, separated by "/"

  string function_id = 4; // Lookup key for retrieving telemetry for this function
  string function_name = 5; // Name of the function, excluding signature

  optional string class_name = 6; // Inner classes may be separated by "."
  optional string language = 7;
}
