// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: telemetry_entity.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// TelemetryEntity describes runtime structure data derived from OpenTelemetry stream analysis.
type TelemetryEntity struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LandscapeTokenId     string                 `protobuf:"bytes,1,opt,name=landscape_token_id,json=landscapeTokenId,proto3" json:"landscape_token_id,omitempty"`
	LandscapeTokenSecret string                 `protobuf:"bytes,2,opt,name=landscape_token_secret,json=landscapeTokenSecret,proto3" json:"landscape_token_secret,omitempty"`
	// Name of the OpenTelemetry instrumentation scope to which this entity's telemetry belongs.
	// See https://opentelemetry.io/docs/concepts/instrumentation-scope/
	InstrumentationScope string  `protobuf:"bytes,3,opt,name=instrumentation_scope,json=instrumentationScope,proto3" json:"instrumentation_scope,omitempty"`
	GitCommitHash        *string `protobuf:"bytes,4,opt,name=git_commit_hash,json=gitCommitHash,proto3,oneof" json:"git_commit_hash,omitempty"`
	// Specifies details depending on the type of entity this message represents
	//
	// Types that are valid to be assigned to EntityDescriptor:
	//
	//	*TelemetryEntity_GenericEntityDescriptor
	//	*TelemetryEntity_CodeDescriptor
	//	*TelemetryEntity_RpcServerDescriptor
	//	*TelemetryEntity_RpcClientDescriptor
	//	*TelemetryEntity_HttpServerDescriptor
	//	*TelemetryEntity_HttpClientDescriptor
	EntityDescriptor isTelemetryEntity_EntityDescriptor `protobuf_oneof:"entity_descriptor"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryEntity) Reset() {
	*x = TelemetryEntity{}
	mi := &file_telemetry_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEntity) ProtoMessage() {}

func (x *TelemetryEntity) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEntity.ProtoReflect.Descriptor instead.
func (*TelemetryEntity) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEntity) GetLandscapeTokenId() string {
	if x != nil {
		return x.LandscapeTokenId
	}
	return ""
}

func (x *TelemetryEntity) GetLandscapeTokenSecret() string {
	if x != nil {
		return x.LandscapeTokenSecret
	}
	return ""
}

func (x *TelemetryEntity) GetInstrumentationScope() string {
	if x != nil {
		return x.InstrumentationScope
	}
	return ""
}

func (x *TelemetryEntity) GetGitCommitHash() string {
	if x != nil && x.GitCommitHash != nil {
		return *x.GitCommitHash
	}
	return ""
}

func (x *TelemetryEntity) GetEntityDescriptor() isTelemetryEntity_EntityDescriptor {
	if x != nil {
		return x.EntityDescriptor
	}
	return nil
}

func (x *TelemetryEntity) GetGenericEntityDescriptor() *GenericEntityDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_GenericEntityDescriptor); ok {
			return x.GenericEntityDescriptor
		}
	}
	return nil
}

func (x *TelemetryEntity) GetCodeDescriptor() *CodeDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_CodeDescriptor); ok {
			return x.CodeDescriptor
		}
	}
	return nil
}

func (x *TelemetryEntity) GetRpcServerDescriptor() *RpcServerDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_RpcServerDescriptor); ok {
			return x.RpcServerDescriptor
		}
	}
	return nil
}

func (x *TelemetryEntity) GetRpcClientDescriptor() *RpcClientDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_RpcClientDescriptor); ok {
			return x.RpcClientDescriptor
		}
	}
	return nil
}

func (x *TelemetryEntity) GetHttpServerDescriptor() *HttpServerDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_HttpServerDescriptor); ok {
			return x.HttpServerDescriptor
		}
	}
	return nil
}

func (x *TelemetryEntity) GetHttpClientDescriptor() *HttpClientDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_HttpClientDescriptor); ok {
			return x.HttpClientDescriptor
		}
	}
	return nil
}

type isTelemetryEntity_EntityDescriptor interface {
	isTelemetryEntity_EntityDescriptor()
}

type TelemetryEntity_GenericEntityDescriptor struct {
	GenericEntityDescriptor *GenericEntityDescriptor `protobuf:"bytes,5,opt,name=generic_entity_descriptor,json=genericEntityDescriptor,proto3,oneof"`
}

type TelemetryEntity_CodeDescriptor struct {
	CodeDescriptor *CodeDescriptor `protobuf:"bytes,6,opt,name=code_descriptor,json=codeDescriptor,proto3,oneof"`
}

type TelemetryEntity_RpcServerDescriptor struct {
	RpcServerDescriptor *RpcServerDescriptor `protobuf:"bytes,7,opt,name=rpc_server_descriptor,json=rpcServerDescriptor,proto3,oneof"`
}

type TelemetryEntity_RpcClientDescriptor struct {
	RpcClientDescriptor *RpcClientDescriptor `protobuf:"bytes,8,opt,name=rpc_client_descriptor,json=rpcClientDescriptor,proto3,oneof"`
}

type TelemetryEntity_HttpServerDescriptor struct {
	HttpServerDescriptor *HttpServerDescriptor `protobuf:"bytes,9,opt,name=http_server_descriptor,json=httpServerDescriptor,proto3,oneof"`
}

type TelemetryEntity_HttpClientDescriptor struct {
	HttpClientDescriptor *HttpClientDescriptor `protobuf:"bytes,10,opt,name=http_client_descriptor,json=httpClientDescriptor,proto3,oneof"`
}

func (*TelemetryEntity_GenericEntityDescriptor) isTelemetryEntity_EntityDescriptor() {}

func (*TelemetryEntity_CodeDescriptor) isTelemetryEntity_EntityDescriptor() {}

func (*TelemetryEntity_RpcServerDescriptor) isTelemetryEntity_EntityDescriptor() {}

func (*TelemetryEntity_RpcClientDescriptor) isTelemetryEntity_EntityDescriptor() {}

func (*TelemetryEntity_HttpServerDescriptor) isTelemetryEntity_EntityDescriptor() {}

func (*TelemetryEntity_HttpClientDescriptor) isTelemetryEntity_EntityDescriptor() {}

// *
// GenericEntityDescriptor describes an entity for which no information apart from the service name
// could be deduced.
type GenericEntityDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // Unqualified variant of the instrumentation scope name
	TelemetryKey  string                 `protobuf:"bytes,3,opt,name=telemetry_key,json=telemetryKey,proto3" json:"telemetry_key,omitempty"` // Lookup key for retrieving telemetry for this entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericEntityDescriptor) Reset() {
	*x = GenericEntityDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericEntityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericEntityDescriptor) ProtoMessage() {}

func (x *GenericEntityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericEntityDescriptor.ProtoReflect.Descriptor instead.
func (*GenericEntityDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{1}
}

func (x *GenericEntityDescriptor) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GenericEntityDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenericEntityDescriptor) GetTelemetryKey() string {
	if x != nil {
		return x.TelemetryKey
	}
	return ""
}

// *
// CodeDescriptor describes a function in code.
type CodeDescriptor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ApplicationName      string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	FileTelemetryKey     string                 `protobuf:"bytes,2,opt,name=file_telemetry_key,json=fileTelemetryKey,proto3" json:"file_telemetry_key,omitempty"`             // Lookup key for retrieving telemetry for this file
	FilePath             string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                                       // File path, separated by "/"
	FunctionTelemetryKey string                 `protobuf:"bytes,4,opt,name=function_telemetry_key,json=functionTelemetryKey,proto3" json:"function_telemetry_key,omitempty"` // Lookup key for retrieving telemetry for this function
	FunctionName         string                 `protobuf:"bytes,5,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`                           // Name of the function, excluding signature
	ClassName            *string                `protobuf:"bytes,6,opt,name=class_name,json=className,proto3,oneof" json:"class_name,omitempty"`                              // Inner classes may be separated by "."
	Language             *string                `protobuf:"bytes,7,opt,name=language,proto3,oneof" json:"language,omitempty"`                                                 // Programming language, e.g. "java"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CodeDescriptor) Reset() {
	*x = CodeDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeDescriptor) ProtoMessage() {}

func (x *CodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeDescriptor.ProtoReflect.Descriptor instead.
func (*CodeDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{2}
}

func (x *CodeDescriptor) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *CodeDescriptor) GetFileTelemetryKey() string {
	if x != nil {
		return x.FileTelemetryKey
	}
	return ""
}

func (x *CodeDescriptor) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CodeDescriptor) GetFunctionTelemetryKey() string {
	if x != nil {
		return x.FunctionTelemetryKey
	}
	return ""
}

func (x *CodeDescriptor) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *CodeDescriptor) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *CodeDescriptor) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// *
// RpcServerDescriptor describes a server-side remote procedure call (e.g. gRPC).
type RpcServerDescriptor struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApplicationName     string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`               // Name of the application or service hosting the RPC server
	ServiceTelemetryKey string                 `protobuf:"bytes,2,opt,name=service_telemetry_key,json=serviceTelemetryKey,proto3" json:"service_telemetry_key,omitempty"` // Lookup key for retrieving telemetry for this RPC service
	ServiceName         string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                           // Fully-qualified name of the RPC service, separated by "."
	MethodTelemetryKey  string                 `protobuf:"bytes,4,opt,name=method_telemetry_key,json=methodTelemetryKey,proto3" json:"method_telemetry_key,omitempty"`    // Lookup key for retrieving telemetry for this RPC method
	MethodName          string                 `protobuf:"bytes,5,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`                              // Name of the RPC method (unqualified) as provided in the service definition
	SystemName          *string                `protobuf:"bytes,6,opt,name=system_name,json=systemName,proto3,oneof" json:"system_name,omitempty"`                        // Name of the used RPC system, e.g. "grpc", "dubbo"
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RpcServerDescriptor) Reset() {
	*x = RpcServerDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcServerDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcServerDescriptor) ProtoMessage() {}

func (x *RpcServerDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcServerDescriptor.ProtoReflect.Descriptor instead.
func (*RpcServerDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{3}
}

func (x *RpcServerDescriptor) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *RpcServerDescriptor) GetServiceTelemetryKey() string {
	if x != nil {
		return x.ServiceTelemetryKey
	}
	return ""
}

func (x *RpcServerDescriptor) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RpcServerDescriptor) GetMethodTelemetryKey() string {
	if x != nil {
		return x.MethodTelemetryKey
	}
	return ""
}

func (x *RpcServerDescriptor) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *RpcServerDescriptor) GetSystemName() string {
	if x != nil && x.SystemName != nil {
		return *x.SystemName
	}
	return ""
}

// *
// RpcClientDescriptor describes a client-side remote procedure call to a server (e.g. gRPC).
type RpcClientDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationName string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"` // Name of the application or service of which the RPC client is part
	TelemetryKey    string                 `protobuf:"bytes,2,opt,name=telemetry_key,json=telemetryKey,proto3" json:"telemetry_key,omitempty"`          // Lookup key for retrieving telemetry for this RPC client
	SystemName      *string                `protobuf:"bytes,3,opt,name=system_name,json=systemName,proto3,oneof" json:"system_name,omitempty"`          // Name of the used RPC system, e.g. "grpc", "dubbo"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RpcClientDescriptor) Reset() {
	*x = RpcClientDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcClientDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcClientDescriptor) ProtoMessage() {}

func (x *RpcClientDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcClientDescriptor.ProtoReflect.Descriptor instead.
func (*RpcClientDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{4}
}

func (x *RpcClientDescriptor) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *RpcClientDescriptor) GetTelemetryKey() string {
	if x != nil {
		return x.TelemetryKey
	}
	return ""
}

func (x *RpcClientDescriptor) GetSystemName() string {
	if x != nil && x.SystemName != nil {
		return *x.SystemName
	}
	return ""
}

// *
// HttpServerDescriptor describes a server-side request to an HTTP API endpoint. An endpoint is
// uniquely identified by the application it belongs to and its route. A single endpoint can support
// multiple HTTP methods.
type HttpServerDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationName string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"` // Name of the application or service to which the HTTP server belongs
	TelemetryKey    string                 `protobuf:"bytes,2,opt,name=telemetry_key,json=telemetryKey,proto3" json:"telemetry_key,omitempty"`          // Lookup key for retrieving telemetry for this API endpoint
	Route           string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`                                            // The matched route template of the request's URL path. Dynamic segments in the path should be represented by placeholders
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                                          // The HTTP request method type, e.g. "GET"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpServerDescriptor) Reset() {
	*x = HttpServerDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpServerDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpServerDescriptor) ProtoMessage() {}

func (x *HttpServerDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpServerDescriptor.ProtoReflect.Descriptor instead.
func (*HttpServerDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{5}
}

func (x *HttpServerDescriptor) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *HttpServerDescriptor) GetTelemetryKey() string {
	if x != nil {
		return x.TelemetryKey
	}
	return ""
}

func (x *HttpServerDescriptor) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *HttpServerDescriptor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// *
// HttpClientDescriptor describes a client-side HTTP request to a server.
type HttpClientDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationName string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"` // Name of the application or service of which the HTTP client is part
	TelemetryKey    string                 `protobuf:"bytes,2,opt,name=telemetry_key,json=telemetryKey,proto3" json:"telemetry_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpClientDescriptor) Reset() {
	*x = HttpClientDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpClientDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpClientDescriptor) ProtoMessage() {}

func (x *HttpClientDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpClientDescriptor.ProtoReflect.Descriptor instead.
func (*HttpClientDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{6}
}

func (x *HttpClientDescriptor) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *HttpClientDescriptor) GetTelemetryKey() string {
	if x != nil {
		return x.TelemetryKey
	}
	return ""
}

var File_telemetry_entity_proto protoreflect.FileDescriptor

const file_telemetry_entity_proto_rawDesc = "" +
	"\n" +
	"\x16telemetry_entity.proto\"\xca\x05\n" +
	"\x0fTelemetryEntity\x12,\n" +
	"\x12landscape_token_id\x18\x01 \x01(\tR\x10landscapeTokenId\x124\n" +
	"\x16landscape_token_secret\x18\x02 \x01(\tR\x14landscapeTokenSecret\x123\n" +
	"\x15instrumentation_scope\x18\x03 \x01(\tR\x14instrumentationScope\x12+\n" +
	"\x0fgit_commit_hash\x18\x04 \x01(\tH\x01R\rgitCommitHash\x88\x01\x01\x12V\n" +
	"\x19generic_entity_descriptor\x18\x05 \x01(\v2\x18.GenericEntityDescriptorH\x00R\x17genericEntityDescriptor\x12:\n" +
	"\x0fcode_descriptor\x18\x06 \x01(\v2\x0f.CodeDescriptorH\x00R\x0ecodeDescriptor\x12J\n" +
	"\x15rpc_server_descriptor\x18\a \x01(\v2\x14.RpcServerDescriptorH\x00R\x13rpcServerDescriptor\x12J\n" +
	"\x15rpc_client_descriptor\x18\b \x01(\v2\x14.RpcClientDescriptorH\x00R\x13rpcClientDescriptor\x12M\n" +
	"\x16http_server_descriptor\x18\t \x01(\v2\x15.HttpServerDescriptorH\x00R\x14httpServerDescriptor\x12M\n" +
	"\x16http_client_descriptor\x18\n" +
	" \x01(\v2\x15.HttpClientDescriptorH\x00R\x14httpClientDescriptorB\x13\n" +
	"\x11entity_descriptorB\x12\n" +
	"\x10_git_commit_hash\"u\n" +
	"\x17GenericEntityDescriptor\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rtelemetry_key\x18\x03 \x01(\tR\ftelemetryKey\"\xc2\x02\n" +
	"\x0eCodeDescriptor\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x12,\n" +
	"\x12file_telemetry_key\x18\x02 \x01(\tR\x10fileTelemetryKey\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x124\n" +
	"\x16function_telemetry_key\x18\x04 \x01(\tR\x14functionTelemetryKey\x12#\n" +
	"\rfunction_name\x18\x05 \x01(\tR\ffunctionName\x12\"\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tH\x00R\tclassName\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\a \x01(\tH\x01R\blanguage\x88\x01\x01B\r\n" +
	"\v_class_nameB\v\n" +
	"\t_language\"\xa0\x02\n" +
	"\x13RpcServerDescriptor\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x122\n" +
	"\x15service_telemetry_key\x18\x02 \x01(\tR\x13serviceTelemetryKey\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x120\n" +
	"\x14method_telemetry_key\x18\x04 \x01(\tR\x12methodTelemetryKey\x12\x1f\n" +
	"\vmethod_name\x18\x05 \x01(\tR\n" +
	"methodName\x12$\n" +
	"\vsystem_name\x18\x06 \x01(\tH\x00R\n" +
	"systemName\x88\x01\x01B\x0e\n" +
	"\f_system_name\"\x9b\x01\n" +
	"\x13RpcClientDescriptor\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x12#\n" +
	"\rtelemetry_key\x18\x02 \x01(\tR\ftelemetryKey\x12$\n" +
	"\vsystem_name\x18\x03 \x01(\tH\x00R\n" +
	"systemName\x88\x01\x01B\x0e\n" +
	"\f_system_name\"\x94\x01\n" +
	"\x14HttpServerDescriptor\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x12#\n" +
	"\rtelemetry_key\x18\x02 \x01(\tR\ftelemetryKey\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\"f\n" +
	"\x14HttpClientDescriptor\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x12#\n" +
	"\rtelemetry_key\x18\x02 \x01(\tR\ftelemetryKeyBAZ?github.com/ExplorViz/otel-collector/common/genproto/telemetrypbb\x06proto3"

var (
	file_telemetry_entity_proto_rawDescOnce sync.Once
	file_telemetry_entity_proto_rawDescData []byte
)

func file_telemetry_entity_proto_rawDescGZIP() []byte {
	file_telemetry_entity_proto_rawDescOnce.Do(func() {
		file_telemetry_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_entity_proto_rawDesc), len(file_telemetry_entity_proto_rawDesc)))
	})
	return file_telemetry_entity_proto_rawDescData
}

var file_telemetry_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_telemetry_entity_proto_goTypes = []any{
	(*TelemetryEntity)(nil),         // 0: TelemetryEntity
	(*GenericEntityDescriptor)(nil), // 1: GenericEntityDescriptor
	(*CodeDescriptor)(nil),          // 2: CodeDescriptor
	(*RpcServerDescriptor)(nil),     // 3: RpcServerDescriptor
	(*RpcClientDescriptor)(nil),     // 4: RpcClientDescriptor
	(*HttpServerDescriptor)(nil),    // 5: HttpServerDescriptor
	(*HttpClientDescriptor)(nil),    // 6: HttpClientDescriptor
}
var file_telemetry_entity_proto_depIdxs = []int32{
	1, // 0: TelemetryEntity.generic_entity_descriptor:type_name -> GenericEntityDescriptor
	2, // 1: TelemetryEntity.code_descriptor:type_name -> CodeDescriptor
	3, // 2: TelemetryEntity.rpc_server_descriptor:type_name -> RpcServerDescriptor
	4, // 3: TelemetryEntity.rpc_client_descriptor:type_name -> RpcClientDescriptor
	5, // 4: TelemetryEntity.http_server_descriptor:type_name -> HttpServerDescriptor
	6, // 5: TelemetryEntity.http_client_descriptor:type_name -> HttpClientDescriptor
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_telemetry_entity_proto_init() }
func file_telemetry_entity_proto_init() {
	if File_telemetry_entity_proto != nil {
		return
	}
	file_telemetry_entity_proto_msgTypes[0].OneofWrappers = []any{
		(*TelemetryEntity_GenericEntityDescriptor)(nil),
		(*TelemetryEntity_CodeDescriptor)(nil),
		(*TelemetryEntity_RpcServerDescriptor)(nil),
		(*TelemetryEntity_RpcClientDescriptor)(nil),
		(*TelemetryEntity_HttpServerDescriptor)(nil),
		(*TelemetryEntity_HttpClientDescriptor)(nil),
	}
	file_telemetry_entity_proto_msgTypes[2].OneofWrappers = []any{}
	file_telemetry_entity_proto_msgTypes[3].OneofWrappers = []any{}
	file_telemetry_entity_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_entity_proto_rawDesc), len(file_telemetry_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_entity_proto_goTypes,
		DependencyIndexes: file_telemetry_entity_proto_depIdxs,
		MessageInfos:      file_telemetry_entity_proto_msgTypes,
	}.Build()
	File_telemetry_entity_proto = out.File
	file_telemetry_entity_proto_goTypes = nil
	file_telemetry_entity_proto_depIdxs = nil
}
