// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: telemetry_entity.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryEntity struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LandscapeTokenId     string                 `protobuf:"bytes,1,opt,name=landscape_token_id,json=landscapeTokenId,proto3" json:"landscape_token_id,omitempty"`
	LandscapeTokenSecret string                 `protobuf:"bytes,2,opt,name=landscape_token_secret,json=landscapeTokenSecret,proto3" json:"landscape_token_secret,omitempty"`
	GitCommitHash        *string                `protobuf:"bytes,4,opt,name=git_commit_hash,json=gitCommitHash,proto3,oneof" json:"git_commit_hash,omitempty"`
	// Types that are valid to be assigned to EntityDescriptor:
	//
	//	*TelemetryEntity_CodeDescriptor
	EntityDescriptor isTelemetryEntity_EntityDescriptor `protobuf_oneof:"entity_descriptor"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryEntity) Reset() {
	*x = TelemetryEntity{}
	mi := &file_telemetry_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEntity) ProtoMessage() {}

func (x *TelemetryEntity) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEntity.ProtoReflect.Descriptor instead.
func (*TelemetryEntity) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEntity) GetLandscapeTokenId() string {
	if x != nil {
		return x.LandscapeTokenId
	}
	return ""
}

func (x *TelemetryEntity) GetLandscapeTokenSecret() string {
	if x != nil {
		return x.LandscapeTokenSecret
	}
	return ""
}

func (x *TelemetryEntity) GetGitCommitHash() string {
	if x != nil && x.GitCommitHash != nil {
		return *x.GitCommitHash
	}
	return ""
}

func (x *TelemetryEntity) GetEntityDescriptor() isTelemetryEntity_EntityDescriptor {
	if x != nil {
		return x.EntityDescriptor
	}
	return nil
}

func (x *TelemetryEntity) GetCodeDescriptor() *CodeDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*TelemetryEntity_CodeDescriptor); ok {
			return x.CodeDescriptor
		}
	}
	return nil
}

type isTelemetryEntity_EntityDescriptor interface {
	isTelemetryEntity_EntityDescriptor()
}

type TelemetryEntity_CodeDescriptor struct {
	CodeDescriptor *CodeDescriptor `protobuf:"bytes,5,opt,name=code_descriptor,json=codeDescriptor,proto3,oneof"`
}

func (*TelemetryEntity_CodeDescriptor) isTelemetryEntity_EntityDescriptor() {}

type CodeDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationName string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	FileId          string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                   // Lookup key for retrieving telemetry for this file
	FilePath        string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // File path, separated by "/"
	FunctionId      string                 `protobuf:"bytes,4,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`       // Lookup key for retrieving telemetry for this function
	FunctionName    string                 `protobuf:"bytes,5,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"` // Name of the function, excluding signature
	ClassName       *string                `protobuf:"bytes,6,opt,name=class_name,json=className,proto3,oneof" json:"class_name,omitempty"`    // Inner classes may be separated by "."
	Language        *string                `protobuf:"bytes,7,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CodeDescriptor) Reset() {
	*x = CodeDescriptor{}
	mi := &file_telemetry_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeDescriptor) ProtoMessage() {}

func (x *CodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeDescriptor.ProtoReflect.Descriptor instead.
func (*CodeDescriptor) Descriptor() ([]byte, []int) {
	return file_telemetry_entity_proto_rawDescGZIP(), []int{1}
}

func (x *CodeDescriptor) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *CodeDescriptor) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CodeDescriptor) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CodeDescriptor) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *CodeDescriptor) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *CodeDescriptor) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *CodeDescriptor) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

var File_telemetry_entity_proto protoreflect.FileDescriptor

const file_telemetry_entity_proto_rawDesc = "" +
	"\n" +
	"\x16telemetry_entity.proto\"\x87\x02\n" +
	"\x0fTelemetryEntity\x12,\n" +
	"\x12landscape_token_id\x18\x01 \x01(\tR\x10landscapeTokenId\x124\n" +
	"\x16landscape_token_secret\x18\x02 \x01(\tR\x14landscapeTokenSecret\x12+\n" +
	"\x0fgit_commit_hash\x18\x04 \x01(\tH\x01R\rgitCommitHash\x88\x01\x01\x12:\n" +
	"\x0fcode_descriptor\x18\x05 \x01(\v2\x0f.CodeDescriptorH\x00R\x0ecodeDescriptorB\x13\n" +
	"\x11entity_descriptorB\x12\n" +
	"\x10_git_commit_hash\"\x98\x02\n" +
	"\x0eCodeDescriptor\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vfunction_id\x18\x04 \x01(\tR\n" +
	"functionId\x12#\n" +
	"\rfunction_name\x18\x05 \x01(\tR\ffunctionName\x12\"\n" +
	"\n" +
	"class_name\x18\x06 \x01(\tH\x00R\tclassName\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\a \x01(\tH\x01R\blanguage\x88\x01\x01B\r\n" +
	"\v_class_nameB\v\n" +
	"\t_languageBAZ?github.com/ExplorViz/otel-collector/common/genproto/telemetrypbb\x06proto3"

var (
	file_telemetry_entity_proto_rawDescOnce sync.Once
	file_telemetry_entity_proto_rawDescData []byte
)

func file_telemetry_entity_proto_rawDescGZIP() []byte {
	file_telemetry_entity_proto_rawDescOnce.Do(func() {
		file_telemetry_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_entity_proto_rawDesc), len(file_telemetry_entity_proto_rawDesc)))
	})
	return file_telemetry_entity_proto_rawDescData
}

var file_telemetry_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_entity_proto_goTypes = []any{
	(*TelemetryEntity)(nil), // 0: TelemetryEntity
	(*CodeDescriptor)(nil),  // 1: CodeDescriptor
}
var file_telemetry_entity_proto_depIdxs = []int32{
	1, // 0: TelemetryEntity.code_descriptor:type_name -> CodeDescriptor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_entity_proto_init() }
func file_telemetry_entity_proto_init() {
	if File_telemetry_entity_proto != nil {
		return
	}
	file_telemetry_entity_proto_msgTypes[0].OneofWrappers = []any{
		(*TelemetryEntity_CodeDescriptor)(nil),
	}
	file_telemetry_entity_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_entity_proto_rawDesc), len(file_telemetry_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_entity_proto_goTypes,
		DependencyIndexes: file_telemetry_entity_proto_depIdxs,
		MessageInfos:      file_telemetry_entity_proto_msgTypes,
	}.Build()
	File_telemetry_entity_proto = out.File
	file_telemetry_entity_proto_goTypes = nil
	file_telemetry_entity_proto_depIdxs = nil
}
