// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/explorviz_token_validator component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("explorviz_token_validator")
	ScopeName = "github.com/ExplorViz/otel-collector/extension/explorviztokenvalidator"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
